# What is Regression of Used Car Prices?

* Predict the price of used cars .

* Use machine learning canvas to know the problem and solution for this project and see my explaination ml canvas on trip advisor hotel reviews notebook

# Load Files

In [1]:
%%time

import pandas as pd

train = pd.read_csv('/kaggle/input/playground-series-s4e9/train.csv')
test = pd.read_csv('/kaggle/input/playground-series-s4e9/test.csv')
sample_submission = pd.read_csv('/kaggle/input/playground-series-s4e9/sample_submission.csv')

CPU times: user 1.18 s, sys: 151 ms, total: 1.33 s
Wall time: 1.72 s

In [2]:
%%time

train.head()

CPU times: user 139 µs, sys: 0 ns, total: 139 µs
Wall time: 130 µs

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500

In [3]:
%%time

test.head()

CPU times: user 83 µs, sys: 17 µs, total: 100 µs
Wall time: 104 µs

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,188533,Land,Rover LR2 Base,2015,98000,Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Beige,None reported,Yes
1,188534,Land,Rover Defender SE,2020,9142,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Silver,Black,None reported,Yes
2,188535,Ford,Expedition Limited,2022,28121,Gasoline,3.5L V6 24V PDI DOHC Twin Turbo,10-Speed Automatic,White,Ebony,None reported,NaN
3,188536,Audi,A6 2.0T Sport,2016,61258,Gasoline,2.0 Liter TFSI,Automatic,Silician Yellow,Black,None reported,NaN
4,188537,Audi,A6 2.0T Premium Plus,2018,59000,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,None reported,Yes

# Check for missing values in the train, test

In [4]:
%%time

missing_values = train.isnull().sum()

missing_values

CPU times: user 155 ms, sys: 3.26 ms, total: 158 ms
Wall time: 158 ms

id                  0
brand               0
model               0
model_year          0
milage              0
fuel_type        5083
engine              0
transmission        0
ext_col             0
int_col             0
accident         2452
clean_title     21419
price               0
dtype: int64

In [5]:
%%time

missing_values = test.isnull().sum()

missing_values

CPU times: user 105 ms, sys: 969 µs, total: 106 ms
Wall time: 105 ms

id                  0
brand               0
model               0
model_year          0
milage              0
fuel_type        3383
engine              0
transmission        0
ext_col             0
int_col             0
accident         1632
clean_title     14239
dtype: int64

# Cleaning Data

In [6]:
%%time

train_data_filled = train.copy()
test_data_filled = test.copy()

CPU times: user 14.5 ms, sys: 3.71 ms, total: 18.2 ms
Wall time: 16.4 ms

In [7]:
%%time

# For categorical/text columns, fill missing values with 'Unknown'
train_data_filled['fuel_type'].fillna('Unknown', inplace=True)
train_data_filled['accident'].fillna('Unknown', inplace=True)
train_data_filled['clean_title'].fillna('Unknown', inplace=True)

test_data_filled['fuel_type'].fillna('Unknown', inplace=True)
test_data_filled['accident'].fillna('Unknown', inplace=True)
test_data_filled['clean_title'].fillna('Unknown', inplace=True)

CPU times: user 96.4 ms, sys: 6.67 ms, total: 103 ms
Wall time: 102 ms

<timed exec>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


<timed exec>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


<timed exec>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


<timed exec>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


<timed exec>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


<timed exec>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [8]:
%%time

# For numeric columns, fill missing values with 0
train_data_filled.fillna(0, inplace=True)
test_data_filled.fillna(0, inplace=True)

CPU times: user 264 ms, sys: 141 µs, total: 264 ms
Wall time: 262 ms

# Check missing values after fillnan

In [9]:
%%time

train_data_filled.isnull().sum()

train_data_filled.head()

CPU times: user 157 ms, sys: 0 ns, total: 157 ms
Wall time: 156 ms

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500

In [10]:
%%time

test_data_filled.isnull().sum()

test_data_filled.head()

CPU times: user 106 ms, sys: 1.15 ms, total: 107 ms
Wall time: 105 ms

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,188533,Land,Rover LR2 Base,2015,98000,Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Beige,None reported,Yes
1,188534,Land,Rover Defender SE,2020,9142,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Silver,Black,None reported,Yes
2,188535,Ford,Expedition Limited,2022,28121,Gasoline,3.5L V6 24V PDI DOHC Twin Turbo,10-Speed Automatic,White,Ebony,None reported,Unknown
3,188536,Audi,A6 2.0T Sport,2016,61258,Gasoline,2.0 Liter TFSI,Automatic,Silician Yellow,Black,None reported,Unknown
4,188537,Audi,A6 2.0T Premium Plus,2018,59000,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,None reported,Yes

# Feature Engineering For Train Data

In [11]:
%%time

train_data_fe = train_data_filled.copy()

CPU times: user 10.2 ms, sys: 7.36 ms, total: 17.5 ms
Wall time: 15.7 ms

* Create a feature for car age based on model_year

In [12]:
%%time

current_year = 2024  # assuming current year
train_data_fe['car_age'] = current_year - train_data_fe['model_year']

train_data_fe['car_age']

CPU times: user 2.91 ms, sys: 0 ns, total: 2.91 ms
Wall time: 2.13 ms

0         17
1         22
2         22
3          7
4          3
          ..
188528     7
188529     6
188530     3
188531     2
188532     8
Name: car_age, Length: 188533, dtype: int64

* Calculate mileage per year

In [13]:
%%time

# To avoid division by zero in case car_age is 0, replace those values with 1

train_data_fe['car_age'] = train_data_fe['car_age'].replace(0, 1)
train_data_fe['mileage_per_year'] = train_data_fe['milage'] / train_data_fe['car_age']

train_data_fe['mileage_per_year']

CPU times: user 1.94 ms, sys: 3 ms, total: 4.94 ms
Wall time: 4.53 ms

0         12529.411765
1          6511.363636
2          6215.045455
3          2785.714286
4          2462.666667
              ...
188528     7000.000000
188529     4766.666667
188530     4550.000000
188531     6947.500000
188532     7437.500000
Name: mileage_per_year, Length: 188533, dtype: float64

# Feature Engineering For Test Data

In [14]:
%%time

test_data_fe = test_data_filled.copy()

CPU times: user 6.38 ms, sys: 8.08 ms, total: 14.5 ms
Wall time: 13 ms

* Create a feature for car age based on model_year

In [15]:
%%time

current_year = 2024  # assuming current year
test_data_fe['car_age'] = current_year - test_data_fe['model_year']

test_data_fe['car_age']

CPU times: user 2.07 ms, sys: 11 µs, total: 2.08 ms
Wall time: 1.47 ms

0          9
1          4
2          2
3          8
4          6
          ..
125685    10
125686     5
125687    12
125688    12
125689     6
Name: car_age, Length: 125690, dtype: int64

* Calculate mileage per year

In [16]:
%%time

test_data_fe['car_age'] = test_data_fe['car_age'].replace(0, 1)
test_data_fe['mileage_per_year'] = test_data_fe['milage'] / test_data_fe['car_age']

test_data_fe['mileage_per_year']

CPU times: user 2.82 ms, sys: 0 ns, total: 2.82 ms
Wall time: 2.51 ms

0         10888.888889
1          2285.500000
2         14060.500000
3          7657.250000
4          9833.333333
              ...
125685     8331.500000
125686     5867.200000
125687     6469.500000
125688     9333.333333
125689    11140.000000
Name: mileage_per_year, Length: 125690, dtype: float64

# Train Using h2o automl

In [17]:
%%time

import h2o
from h2o.automl import H2OAutoML

# Start the H2O cluster
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.24" 2024-07-16; OpenJDK Runtime Environment (build 11.0.24+8-post-Ubuntu-1ubuntu322.04); OpenJDK 64-Bit Server VM (build 11.0.24+8-post-Ubuntu-1ubuntu322.04, mixed mode, sharing)
  Starting server from /opt/conda/lib/python3.10/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpkcczhmqj
  JVM stdout: /tmp/tmpkcczhmqj/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpkcczhmqj/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ----------------------------------
H2O_cluster_uptime:         02 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.4
H2O_cluster_version_age:    1 month and 26 days
H2O_cluster_name:           H2O_from_python_unknownUser_sh8uq7
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    7.250 Gb
H2O_cluster_total_cores:    4
H2O_cluster_allowed_cores:  4
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.10.14 final
--------------------------  ----------------------------------

CPU times: user 315 ms, sys: 69.7 ms, total: 384 ms
Wall time: 7.76 s

In [18]:
%%time

# Convert Pandas DataFrames to H2O frames
train_h2o = h2o.H2OFrame(train_data_filled)
test_h2o = h2o.H2OFrame(test_data_filled)

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
CPU times: user 4.19 s, sys: 218 ms, total: 4.4 s
Wall time: 10.2 s

* Set price column as target

In [19]:
%%time

# Define target and predictors
target = 'price'
predictors = train_h2o.columns

CPU times: user 15 µs, sys: 1 µs, total: 16 µs
Wall time: 21.2 µs

In [20]:
%%time

predictors.remove('id')

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 9.3 µs

In [21]:
%%time

# Split the training data into train and validation sets
train, valid = train_h2o.split_frame(ratios=[0.8], seed=42)

CPU times: user 96 ms, sys: 3.09 ms, total: 99.1 ms
Wall time: 976 ms

In [22]:
%%time

# Initialize H2O AutoML
aml = H2OAutoML(max_models=20, seed=42, exclude_algos=["DeepLearning"], stopping_metric='RMSE', max_runtime_secs=1000)

# Train the model
aml.train(x=predictors, y=target, training_frame=train, validation_frame=valid)

AutoML progress: |
02:55:07.94: User specified a validation frame with cross-validation still enabled. Please note that the models will still be validated using cross-validation only, the validation frame will be used to provide purely informative validation metrics on the trained models.

███████████████████████████████████████████████████████████████| (done) 100%
CPU times: user 6.61 s, sys: 534 ms, total: 7.14 s
Wall time: 16min 41s

Model Details
=============
H2OGradientBoostingEstimator : Gradient Boosting Machine
Model Key: GBM_1_AutoML_1_20240905_25506


Model Summary:
    number_of_trees    number_of_internal_trees    model_size_in_bytes    min_depth    max_depth    mean_depth    min_leaves    max_leaves    mean_leaves
--  -----------------  --------------------------  ---------------------  -----------  -----------  ------------  ------------  ------------  -------------
    26                 26                          664064                 15           15           15            122           837           534.462

ModelMetricsRegression: gbm
** Reported on train data. **

MSE: 4939656036.4357
RMSE: 70282.68660513555
MAE: 17721.75987309496
RMSLE: 0.5042745823678313
Mean Residual Deviance: 4939656036.4357

ModelMetricsRegression: gbm
** Reported on validation data. **

MSE: 4111706926.7537503
RMSE: 64122.59295095412
MAE: 19288.841458198556
RMSLE: 0.5547390925513246
Mean Residual Deviance: 4111706926.7537503

ModelMetricsRegression: gbm
** Reported on cross-validation data. **

MSE: 5660611999.010816
RMSE: 75237.03874429679
MAE: 19815.513864473378
RMSLE: NaN
Mean Residual Deviance: 5660611999.010816

Cross-Validation Metrics Summary:
                        mean         sd           cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
----------------------  -----------  -----------  ------------  ------------  ------------  ------------  ------------
aic                     nan          0            nan           nan           nan           nan           nan
loglikelihood           nan          0            nan           nan           nan           nan           nan
mae                     19965.5      256.345      20070         19810.1       20364.2       19856         19727
mean_residual_deviance  5.67915e+09  6.59442e+08  5.6119e+09    5.62042e+09   6.79203e+09   5.13102e+09   5.24037e+09
mse                     5.67915e+09  6.59442e+08  5.6119e+09    5.62042e+09   6.79203e+09   5.13102e+09   5.24037e+09
r2                      0.129806     0.0122248    0.13697       0.121824      0.112164      0.139772      0.138302
residual_deviance       5.67915e+09  6.59442e+08  5.6119e+09    5.62042e+09   6.79203e+09   5.13102e+09   5.24037e+09
rmse                    75263.5      4265.7       74912.6       74969.4       82413.8       71631.1       72390.4
rmsle                   0.554824     0            nan           nan           nan           0.554824      nan

Scoring History:
    timestamp            duration    number_of_trees    training_rmse    training_mae    training_deviance    validation_rmse    validation_mae    validation_deviance
--  -------------------  ----------  -----------------  ---------------  --------------  -------------------  -----------------  ----------------  ---------------------
    2024-09-05 02:56:25  32.547 sec  0                  80745.9          29197.6         6.5199e+09           70571.5            28834.8           4.98034e+09
    2024-09-05 02:56:26  34.031 sec  5                  75783.4          22944.2         5.74313e+09          66261.4            22994.9           4.39057e+09
    2024-09-05 02:56:28  35.353 sec  10                 73375.7          20066.5         5.38399e+09          64680.3            20592.6           4.18354e+09
    2024-09-05 02:56:28  36.303 sec  15                 71963            18712.9         5.17867e+09          64143.4            19624.7           4.11438e+09
    2024-09-05 02:56:29  37.268 sec  20                 71038.4          18056.7         5.04645e+09          64032.8            19327.5           4.1002e+09
    2024-09-05 02:56:30  38.094 sec  25                 70389.5          17755.6         4.95468e+09          64089.5            19277.7           4.10746e+09
    2024-09-05 02:56:30  38.299 sec  26                 70282.7          17721.8         4.93966e+09          64122.6            19288.8           4.11171e+09

Variable Importances:
variable      relative_importance    scaled_importance    percentage
------------  ---------------------  -------------------  ------------
engine        4.08165e+14            1                    0.337562
milage        3.21115e+14            0.786727             0.265569
ext_col       1.45533e+14            0.356555             0.120359
model_year    1.04897e+14            0.256996             0.0867522
int_col       6.53667e+13            0.160148             0.0540598
brand         6.28278e+13            0.153927             0.0519601
transmission  5.47553e+13            0.13415              0.0452839
model         4.16782e+13            0.102111             0.0344689
accident      2.52908e+12            0.00619622           0.00209161
clean_title   1.6545e+12             0.00405352           0.00136831
fuel_type     6.34001e+11            0.00155329           0.000524333

[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [23]:
%%time 

# View the leaderboard
lb = aml.leaderboard
print(lb)

model_id                                           rmse          mse      mae       rmsle    mean_residual_deviance
GBM_1_AutoML_1_20240905_25506                   75237    5.66061e+09  19815.5  nan                      5.66061e+09
XGBoost_grid_1_AutoML_1_20240905_25506_model_4  75351    5.67777e+09  20460.3    0.579565               5.67777e+09
GBM_2_AutoML_1_20240905_25506                   75554.9  5.70854e+09  19830.1  nan                      5.70854e+09
GBM_3_AutoML_1_20240905_25506                   75810.1  5.74718e+09  20026.5  nan                      5.74718e+09
XRT_1_AutoML_1_20240905_25506                   75836.3  5.75114e+09  20790      0.587401               5.75114e+09
GBM_4_AutoML_1_20240905_25506                   75873.3  5.75676e+09  20024.2  nan                      5.75676e+09
GBM_5_AutoML_1_20240905_25506                   76240.5  5.81262e+09  19852.2  nan                      5.81262e+09
XGBoost_3_AutoML_1_20240905_25506               76426    5.84093e+09  20800.9  nan                      5.84093e+09
XGBoost_1_AutoML_1_20240905_25506               76599.1  5.86742e+09  21112.2  nan                      5.86742e+09
XGBoost_2_AutoML_1_20240905_25506               77022.6  5.93248e+09  21104.4  nan                      5.93248e+09
[16 rows x 6 columns]

CPU times: user 7.4 ms, sys: 26 µs, total: 7.42 ms
Wall time: 11.2 ms

In [24]:
%%time

# Make predictions on the test set
preds = aml.predict(test_h2o)

gbm prediction progress: |███████████████████████████████████████████████████████| (done) 100%
CPU times: user 48.6 ms, sys: 3.22 ms, total: 51.8 ms
Wall time: 1.89 s

/opt/conda/lib/python3.10/site-packages/h2o/job.py:81: UserWarning: Test/Validation dataset column 'model' has levels not trained on: ["allroad 2.7T"]
  warnings.warn(w)
/opt/conda/lib/python3.10/site-packages/h2o/job.py:81: UserWarning: Test/Validation dataset column 'engine' has levels not trained on: ["177.0HP 1.6L 4 Cylinder Engine Plug-In Electric/Gas"]
  warnings.warn(w)

In [25]:
%%time

# Convert H2OFrame predictions to a pandas DataFrame
predictions_df = preds.as_data_frame()

/opt/conda/lib/python3.10/site-packages/h2o/frame.py:1981: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"

CPU times: user 48.4 ms, sys: 1.9 ms, total: 50.3 ms
Wall time: 220 ms

In [26]:
%%time

# Prepare the submission file
submission = pd.DataFrame({'id': test_data_filled['id'], 'price': predictions_df['predict']})

CPU times: user 1.53 ms, sys: 887 µs, total: 2.42 ms
Wall time: 1.6 ms

In [27]:
%%time

# Create submission file
submission.to_csv('submission.csv', index=False)

CPU times: user 328 ms, sys: 4.72 ms, total: 333 ms
Wall time: 333 ms

In [28]:
%%time

# Predicted price of used cars

submission.head()

CPU times: user 170 µs, sys: 13 µs, total: 183 µs
Wall time: 177 µs

       id         price
0  188533  20256.271804
1  188534  70673.226416
2  188535  50896.313721
3  188536  23640.561309
4  188537  29796.132918